/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_m210projects_Build_Render_Software_JniA */

#ifndef _Included_ru_m210projects_Build_Render_Software_JniA
#define _Included_ru_m210projects_Build_Render_Software_JniA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jniinit
 * Signature: ([[B[I)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jniinit
  (JNIEnv *, jobject, jobjectArray, jintArray);
  
/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetframeplace
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetframeplace
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetvlinebpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetvlinebpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnifixtransluscence
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnifixtransluscence
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisettransnormal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisettransnormal
  (JNIEnv *, jobject);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisettransreverse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisettransreverse
  (JNIEnv *, jobject);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnidrawpixel
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnidrawpixel
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisethlinesizes
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisethlinesizes
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetpalookupaddress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetpalookupaddress
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetuphlineasm4
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetuphlineasm4
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnihlineasm4
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnihlineasm4
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetupslopevlin
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetupslopevlin
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnislopevlin
 * Signature: (IIIIIIII[II)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnislopevlin
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jintArray, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetupvlineasm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetupvlineasm
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnivlineasm1
 * Signature: (IIIII[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnivlineasm1
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetupmvlineasm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetupmvlineasm
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnimvlineasm1
 * Signature: (IIIII[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnimvlineasm1
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetuptvlineasm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetuptvlineasm
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnitvlineasm1
 * Signature: (IIIII[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnitvlineasm1
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisethlineincs
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisethlineincs
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetuphline
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetuphline
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnimsethlineshift
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnimsethlineshift
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnimhline
 * Signature: ([BIIIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnimhline
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnitsethlineshift
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnitsethlineshift
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnithline
 * Signature: ([BIIIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnithline
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetupspritevline
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetupspritevline
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnispritevline
 * Signature: (III[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnispritevline
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnimsetupspritevline
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnimsetupspritevline
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnimspritevline
 * Signature: (III[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnimspritevline
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnitsetupspritevline
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnitsetupspritevline
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnitspritevline
 * Signature: (III[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnitspritevline
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnisetupdrawslab
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnisetupdrawslab
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     ru_m210projects_Build_Render_Software_JniA
 * Method:    jnidrawslab
 * Signature: (IIII[BII)V
 */
JNIEXPORT void JNICALL Java_ru_m210projects_Build_Render_Software_JniA_jnidrawslab
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
